name: uiohook_dart
description: Cross-platform Desktop keyboard and mouse hooking library
version: 0.0.1
homepage: https://github.com/rohitsangwan01/uiohook_dart
repository: https://github.com/rohitsangwan01/uiohook_dart
issue_tracker: https://github.com/rohitsangwan01/uiohook_dart/issues

environment:
  sdk: ^3.4.3

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  ffigen: ^12.0.0

platforms:
  linux:
  macos:
  windows:

ffigen:
  output: 'lib/src/generated/generated_bindings.dart'
  headers:
    entry-points:
        - 'uiohook_header/uiohook.h'
