name: uiohook_dart
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  ffigen: ^12.0.0

ffigen:
  output: 'lib/src/generated/generated_bindings.dart'
  headers:
    entry-points:
        - 'uiohook_header/uiohook.h'
