name: uiohook_flutter
description: "Cross-platform Desktop keyboard and mouse hooking library"
version: 0.0.1
homepage: https://github.com/rohitsangwan01/uiohook_dart
repository: https://github.com/rohitsangwan01/uiohook_dart
issue_tracker: https://github.com/rohitsangwan01/uiohook_dart/issues

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  linux:
  macos:
  windows:

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: UiohookFlutterPlugin
      macos:
        pluginClass: UiohookFlutterPlugin